<?php
/**
 * This file is generated by WP Starter package, and contains base configuration of the WordPress.
 *
 * All the configuration constants used by WordPress are set via environment variables.
 * Default settings are provided in this file for most common settings, however database settings
 * are required, you can get them from your web host.
 *
 * A sample .env file (.env.example) should be placed in the root of your project, rename it to .env
 * and edit it according to your needs.
 */

/**
 * Composer autoload.
 */
require_once realpath(dirname(__DIR__).'/web/wp-content/vendor'.'/autoload.php');

/**
 * A reference to `.env` folder path.
 */
define('WPSTARTER_PATH', dirname(__DIR__));

/**
 * Configuration constants.
 *
 * Use environment variables to set WordPress constants.
 * Mandatory settings:
 * - DB_NAME
 * - DB_USER
 * - DB_PASSWORD
 *
 * @var array $env All the variables stored in environment variables
 */
$env = WCM\WPStarter\Helpers::settings(dirname(__DIR__), '.env');

global $table_prefix;
array_walk($env, function ($value, $name) {
    switch ($name) {
        case 'DB_TABLE_PREFIX':
            $GLOBALS['table_prefix'] = preg_replace('#[^\w]#', '', $value);
            break;
        default:
            defined($name) || define($name, $value);
            break;
    }
});

/**
 * Set optional database settings if not already set
 */
defined('DB_HOST')    || define('DB_HOST',    'localhost');
defined('DB_CHARSET') || define('DB_CHARSET', 'utf8');
defined('DB_COLLATE') || define('DB_COLLATE', '');

/**
 * Set WordPress Database Table prefix if not already set.
 *
 * @global string $table_prefix
 */
if (! isset($table_prefix) || empty($table_prefix)) {
    $table_prefix = 'wp_';
}

/**
 * Set unique authentication keys if not already set via environment variables.
 */
define('AUTH_KEY',         'ost-d1x`T&|$F&6Hg_/SIXG,~HLS{!yZ-72Xd-CBk_(h+W,k_`2Ute@tRow<yTRY');
define('SECURE_AUTH_KEY',  '!`FOlt<L@=t5npcRv!gMPRu<[O1g<*_=+Z+tB.w4.9B9On5+6m}9582[Eq|:hp4D');
define('LOGGED_IN_KEY',    ';EMp![}Ib-4QIJPSQK:MBrROy%BYlt883o9Fl9mDtwWMFz)<=CkH@U+qnmL8O_qY');
define('NONCE_KEY',        'DiY}1upG r@V7n#v(7~|TplZU]r_0uu<kc3xzm)W|i`*S<L[T)DsI_?c-&YpgKmB');
define('AUTH_SALT',        '[Kzx{R56ol}B+`*5M0AmfDN2Ce0i oa:*`n*N7,Fvq.5mL`V+Y $K2eq|yDZzs 9');
define('SECURE_AUTH_SALT', '.63v).Tz?8;;cptt5(lQFBf`#{eAHw),[!bn|?5,Bc,UQ7JrHFIky}J,(.}lA`2F');
define('LOGGED_IN_SALT',   'A(.^xm% nyUerQD8p0~Pq|yuZ&^M%e(L*=D{WCjwchY]IOCAHX~kBc B:9B-{V}v');
define('NONCE_SALT',       'm],Enk3Fe4jf!,Ez56CT_?05;~[.,.LbIJB,Vu65f#{A&(6<ec(OlrJB0PBx9d:x');

/**
 * Environment-aware settings. Be creative, but avoid to set sensitive settings here.
 */
$environment = getenv('WORDPRESS_ENV');
defined( 'WP_ENVIRONMENT_TYPE' ) || define( 'WP_ENVIRONMENT_TYPE', $environment );
switch ($environment) {

    case 'development':
        defined('WP_DEBUG')         || define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') || define('WP_DEBUG_DISPLAY', true);
        defined('WP_DEBUG_LOG')     || define('WP_DEBUG_LOG',     false);
        defined('SAVEQUERIES')      || define('SAVEQUERIES',      true);
        defined('SCRIPT_DEBUG')     || define('SCRIPT_DEBUG',     true);
        break;

    case 'staging':
        defined('WP_DEBUG')         || define('WP_DEBUG',         true);
        defined('WP_DEBUG_DISPLAY') || define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     || define('WP_DEBUG_LOG',     true);
        defined('SCRIPT_DEBUG')     || define('SCRIPT_DEBUG',     true);
        break;

    case 'production':
    default:
        defined('WP_DEBUG')         || define('WP_DEBUG',         false);
        defined('WP_DEBUG_DISPLAY') || define('WP_DEBUG_DISPLAY', false);
        defined('WP_DEBUG_LOG')     || define('WP_DEBUG_LOG',     false);
        defined('SCRIPT_DEBUG')     || define('SCRIPT_DEBUG',     false);
        break;
}

/**
 * Fix HTTPS behind load balancers.
 *
 * @link https://core.trac.wordpress.org/ticket/31288
 */
if (
    isset($_SERVER['HTTP_X_FORWARDED_PROTO'])
	&& 'https' === strtolower($_SERVER['HTTP_X_FORWARDED_PROTO'])
) {
	$_SERVER[ 'HTTPS' ] = 'on';
}

/**
 * Set WordPress paths and URLs if not set via environment variables.
 */
if (! defined('WP_HOME')) {
    $server = filter_input_array(INPUT_SERVER, array(
        'HTTPS'       => FILTER_SANITIZE_STRING,
        'SERVER_PORT' => FILTER_SANITIZE_NUMBER_INT,
        'SERVER_NAME' => FILTER_SANITIZE_URL,
    ));
    $secure = in_array((string) $server['HTTPS'], array('on', '1'), true);
    $scheme = $secure ? 'https://' : 'http://';
    $name   = $server['SERVER_NAME'] ? : 'ndigitals.ddev.site';
    define('WP_HOME', $scheme.$name);
}

defined('ABSPATH')    || define('ABSPATH',    realpath(dirname(__DIR__).'/web/wp'));
defined('WP_SITEURL') || define('WP_SITEURL', rtrim(WP_HOME, '/').'/wp');

/**
 * Define content constants only if needed, or network install screen will complain for no reason
 */
$custom_content_dir = realpath(dirname(__DIR__).'/web/wp-content') !== realpath(ABSPATH.'/wp-content');
if ($custom_content_dir && ! defined('WP_CONTENT_DIR')) {
    define('WP_CONTENT_DIR', realpath(dirname(__DIR__).'/web/wp-content'));
}
if ($custom_content_dir && ! (defined('MULTISITE') && MULTISITE) && ! defined('WP_CONTENT_URL')) {
    define('WP_CONTENT_URL', rtrim(WP_HOME, '/').'/wp-content');
}

// Include for ddev-managed settings in wp-config-ddev.php.
$ddev_settings = dirname( __FILE__ ) . '/wp-config-ddev.php';
if ( is_readable( $ddev_settings ) && ! defined( 'DB_USER' ) ) {
	require_once( $ddev_settings );
}

/**
 * Clean up.
 */
unset($env, $environment, $server, $secure, $scheme, $name, $custom_content_dir);

/**
 * Allows to load MU plugins in subfolders.
 */
WCM\WPStarter\Helpers::addHook(
    'muplugins_loaded',
    new WCM\WPStarter\MuLoader\MuLoader(),
    PHP_INT_MAX,
    0
);

/**
 * Register default themes inside WordPress package wp-content folder.
 */
WCM\WPStarter\Helpers::addHook('plugins_loaded', function () {
    WCM\WPStarter\Helpers::loadThemeFolder(true);
}, 0);

/**
 * Sets up WordPress vars and included files.
 */
require_once ABSPATH.'/wp-settings.php';
